version: '3'
services: 
  gateway:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    environment:
      - DB_CONNECTION_URL=postgres://test:test@postgres:5432/e2e_test?sslmode=disable
    ports:
      - 8090:8090
    depends_on:
      - postgres
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        make migrate
        ./cmd/gateway/gateway

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 8123:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./build/ci/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

#  integration_tests:
#    build:
#      context: .
#      dockerfile: build/package/Dockerfile.test
#    depends_on:
#      - gateway
#    environment:
#      - HOST=http://gateway:8090

volumes:
  pg-data:
    name: pg-data